const LANG_DICT = {
    zh_hk: {
        title: "JL 智能投研",
        subtitle: "AI 金融年報分析與自動審計系統",
        upload: "上傳年報 PDF",
        uploadLabel: "選擇本地年報 PDF 文檔",
        dropzoneTitle: "拖放或點擊選擇年報 PDF (Max 50MB)",
        pdfMode: "📄 物理 PDF 研報",
        edgarMode: "🏛️ SEC EDGAR 系統",
        runAnalysisBtn: "啟動 AI 深度投研分析",
        analystTitle: "AI 股票分析師 (JL Stock Analyst)",
        analystDesc: "支持直接解析本地 PDF，或直連美國證監會 SEC EDGAR 數據庫，自動出具 Bluebook 標準的學術級引文研報。",
        reportTypeLabel: "選擇分析報告類型",
        waiting: "等待上傳中",
        waitHint: "上傳財報後自動解鎖流式分析看板",
        noResultsTitle: "年報分析尚未開始",
        noResultsDesc: "請在左側選擇上傳 PDF 或輸入美股 Ticker 啟動分析",
        originalDoc: "📄 原始報告數據源已鏈接",
        ragasScore: "📊 RAG 檢索生成質量客觀審計 (Ragas Score)",
        founder: "創始人",
        version: "AI Stock Analyst Enterprise v2.0 (Live)"
    },
    zh_cn: {
        title: "JL 智能投研",
        subtitle: "AI 金融年报分析与自动审计系统",
        upload: "上传年报 PDF",
        uploadLabel: "选择本地年报 PDF 文档",
        dropzoneTitle: "拖放或点击选择年报 PDF (Max 50MB)",
        pdfMode: "📄 物理 PDF 研报",
        edgarMode: "🏛️ SEC EDGAR 系统",
        runAnalysisBtn: "启动 AI 深度投研分析",
        analystTitle: "AI 股票分析师 (JL Stock Analyst)",
        analystDesc: "支持直接解析本地 PDF，或直连美国证监会 SEC EDGAR 数据库，自动出具 Bluebook 标准的学术级引文研报。",
        reportTypeLabel: "选择分析报告类型",
        waiting: "等待上传中",
        waitHint: "上传财报后自动解锁流式分析看板",
        noResultsTitle: "年报分析尚未开始",
        noResultsDesc: "请在左侧选择上传 PDF 或输入美股 Ticker 启动分析",
        originalDoc: "📄 原始报告数据源已链接",
        ragasScore: "📊 RAG 检索生成质量客观审计 (Ragas Score)",
        founder: "创始人",
        version: "AI Stock Analyst Enterprise v2.0 (Live)"
    },
    en: {
        title: "JL Intelligence",
        subtitle: "AI Stock Analysis & Automated Ragas Audit System",
        upload: "Upload Annual Report",
        uploadLabel: "Select Local Annual Report PDF Document",
        dropzoneTitle: "Drag & drop or click to choose PDF (Max 50MB)",
        pdfMode: "📄 Physical PDF Mode",
        edgarMode: "🏛️ SEC EDGAR System",
        runAnalysisBtn: "Run AI Deep Valuation Engine",
        analystTitle: "AI Stock Analyst (JL Stock Analyst)",
        analystDesc: "Parses local corporate PDFs or connects directly to SEC EDGAR database to generate institutional reports with Bluebook-standard footnotes.",
        reportTypeLabel: "Select Valuation Model",
        waiting: "Awaiting File",
        waitHint: "Upload a document to unlock the live Ragas streaming board",
        noResultsTitle: "No Active Valuation",
        noResultsDesc: "Upload a PDF or enter a stock ticker on the left panel to begin.",
        originalDoc: "📄 Original Report Data Source Connected",
        ragasScore: "📊 RAG Retrieval Quality Audit (Ragas Score)",
        founder: "Founder",
        version: "AI Stock Analyst Enterprise v2.0 (Live)"
    }
};
